apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: random-logger-svc
spec:
  replicas: 3  #Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: random-logger-svc
  template:
    metadata:
      labels:
        app: random-logger-svc
    spec:
      containers:
        - name: random-logger-container
          image: raje/random-logger-svc # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster